// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package dag

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	Timestamp            string            `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Address              string            `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Previous             string            `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Properties           map[string]string `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Edges                map[string]string `protobuf:"bytes,5,rep,name=edges,proto3" json:"edges,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Branches             []string          `protobuf:"bytes,6,rep,name=branches,proto3" json:"branches,omitempty"`
	Data                 []byte            `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	PowTarget            int32             `protobuf:"varint,8,opt,name=powTarget,proto3" json:"powTarget,omitempty"`
	PowNonce             int64             `protobuf:"varint,9,opt,name=powNonce,proto3" json:"powNonce,omitempty"`
	Hash                 string            `protobuf:"bytes,10,opt,name=hash,proto3" json:"hash,omitempty"`
	PubKey               string            `protobuf:"bytes,11,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Signature            string            `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *Node) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Node) GetEdges() map[string]string {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *Node) GetBranches() []string {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *Node) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Node) GetPowTarget() int32 {
	if m != nil {
		return m.PowTarget
	}
	return 0
}

func (m *Node) GetPowNonce() int64 {
	if m != nil {
		return m.PowNonce
	}
	return 0
}

func (m *Node) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Node) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Node) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*Node)(nil), "node.Node")
	proto.RegisterMapType((map[string]string)(nil), "node.Node.EdgesEntry")
	proto.RegisterMapType((map[string]string)(nil), "node.Node.PropertiesEntry")
}

func init() {
	proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7)
}

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0xdd, 0xa4, 0x1f, 0xd3, 0x82, 0xb2, 0xa8, 0x0c, 0xc1, 0x43, 0xf0, 0x14, 0x10, 0x7a,
	0xd0, 0x4b, 0x29, 0x78, 0x11, 0x7a, 0x12, 0x8a, 0x04, 0x4f, 0xde, 0xb6, 0xdd, 0x21, 0x0d, 0xda,
	0xec, 0xb2, 0xbb, 0x69, 0xe9, 0xbf, 0xf6, 0x27, 0xc8, 0x6e, 0xda, 0xb4, 0x78, 0xf3, 0xf6, 0xde,
	0x9b, 0x7d, 0x99, 0x79, 0x8f, 0x00, 0xd4, 0x4a, 0xd2, 0x54, 0x1b, 0xe5, 0x14, 0x8f, 0x3d, 0x7e,
	0xf8, 0x61, 0x10, 0x2f, 0x95, 0x24, 0x7e, 0x0f, 0x23, 0x57, 0x6d, 0xc9, 0x3a, 0xb1, 0xd5, 0x18,
	0x65, 0x51, 0x3e, 0x2a, 0xce, 0x02, 0x47, 0x18, 0x08, 0x29, 0x0d, 0x59, 0x8b, 0xbd, 0x30, 0x3b,
	0x51, 0x9e, 0xc2, 0x50, 0x1b, 0xda, 0x55, 0xaa, 0xb1, 0xc8, 0xc2, 0xa8, 0xe3, 0x7c, 0x0e, 0xa0,
	0x8d, 0xd2, 0x64, 0x5c, 0x45, 0x16, 0xe3, 0x8c, 0xe5, 0xe3, 0xa7, 0x74, 0x1a, 0x6e, 0xf0, 0x3b,
	0xa7, 0xef, 0xdd, 0x70, 0x51, 0x3b, 0x73, 0x28, 0x2e, 0x5e, 0xf3, 0x47, 0x48, 0x48, 0x96, 0x64,
	0x31, 0x09, 0xb6, 0xdb, 0x0b, 0xdb, 0xc2, 0xeb, 0xad, 0xa3, 0x7d, 0xe3, 0x8f, 0x58, 0x19, 0x51,
	0xaf, 0x37, 0x64, 0xb1, 0x9f, 0x31, 0x7f, 0xc4, 0x89, 0x73, 0x0e, 0xb1, 0x14, 0x4e, 0xe0, 0x20,
	0x8b, 0xf2, 0x49, 0x11, 0xb0, 0x0f, 0xab, 0xd5, 0xfe, 0x43, 0x98, 0x92, 0x1c, 0x0e, 0xb3, 0x28,
	0x4f, 0x8a, 0xb3, 0x10, 0x22, 0xa9, 0xfd, 0x52, 0xd5, 0x6b, 0xc2, 0x51, 0x16, 0xe5, 0xac, 0xe8,
	0xb8, 0xff, 0xda, 0x46, 0xd8, 0x0d, 0x42, 0x88, 0x1a, 0x30, 0xbf, 0x83, 0xbe, 0x6e, 0x56, 0x6f,
	0x74, 0xc0, 0x71, 0x50, 0x8f, 0xcc, 0x6f, 0xb1, 0x55, 0x59, 0x0b, 0xd7, 0x18, 0xc2, 0x49, 0x5b,
	0x69, 0x27, 0xa4, 0x2f, 0x70, 0xf5, 0x27, 0x3f, 0xbf, 0x06, 0xf6, 0x45, 0x87, 0x63, 0xfb, 0x1e,
	0xf2, 0x1b, 0x48, 0x76, 0xe2, 0xbb, 0xa1, 0x63, 0xeb, 0x2d, 0x99, 0xf7, 0x66, 0x51, 0x3a, 0x03,
	0x38, 0xf7, 0xf0, 0x1f, 0xe7, 0x6b, 0xf2, 0xc9, 0xa4, 0x28, 0x57, 0xfd, 0xf0, 0x1b, 0x3c, 0xff,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x19, 0x66, 0xc0, 0x14, 0x02, 0x00, 0x00,
}
