// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package datachain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Seq                  int64             `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp            string            `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Address              string            `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Previous             string            `protobuf:"bytes,5,opt,name=previous,proto3" json:"previous,omitempty"`
	Properties           map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 []byte            `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	PowTarget            int32             `protobuf:"varint,8,opt,name=powTarget,proto3" json:"powTarget,omitempty"`
	PowNonce             int64             `protobuf:"varint,9,opt,name=powNonce,proto3" json:"powNonce,omitempty"`
	Hash                 string            `protobuf:"bytes,10,opt,name=hash,proto3" json:"hash,omitempty"`
	PubKey               string            `protobuf:"bytes,11,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Signature            string            `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Transaction) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Transaction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Transaction) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Transaction) GetPrevious() string {
	if m != nil {
		return m.Previous
	}
	return ""
}

func (m *Transaction) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetPowTarget() int32 {
	if m != nil {
		return m.PowTarget
	}
	return 0
}

func (m *Transaction) GetPowNonce() int64 {
	if m != nil {
		return m.PowNonce
	}
	return 0
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Transaction) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*Transaction)(nil), "datachain.Transaction")
	proto.RegisterMapType((map[string]string)(nil), "datachain.Transaction.PropertiesEntry")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x4f, 0x4b, 0x3b, 0x31,
	0x10, 0x65, 0xbb, 0xfd, 0xb7, 0xb3, 0x85, 0xdf, 0xcf, 0x20, 0x32, 0x14, 0x0f, 0x8b, 0x07, 0xd9,
	0xd3, 0x1e, 0xf4, 0x22, 0x82, 0x17, 0x41, 0x2f, 0x82, 0x48, 0xe8, 0xc9, 0x5b, 0xda, 0x0e, 0x6d,
	0xd0, 0x26, 0x31, 0xc9, 0xb6, 0xec, 0x17, 0xf2, 0x73, 0x4a, 0xb2, 0x75, 0xb7, 0x78, 0x7b, 0xef,
	0xcd, 0x4c, 0xf2, 0xe6, 0x0d, 0x9c, 0x79, 0x2b, 0x94, 0x13, 0x2b, 0x2f, 0xb5, 0xaa, 0x8c, 0xd5,
	0x5e, 0xb3, 0x6c, 0x2d, 0xbc, 0x58, 0x6d, 0x85, 0x54, 0x57, 0xdf, 0x29, 0xe4, 0x8b, 0xbe, 0x81,
	0xfd, 0x87, 0xd4, 0xd1, 0x17, 0x26, 0x45, 0x52, 0xa6, 0x3c, 0x40, 0x76, 0x09, 0x99, 0x97, 0x3b,
	0x72, 0x5e, 0xec, 0x0c, 0x0e, 0x8a, 0xa4, 0xcc, 0x78, 0x2f, 0x30, 0x06, 0x43, 0xdf, 0x18, 0xc2,
	0x34, 0x16, 0x22, 0x66, 0x08, 0x13, 0xb1, 0x5e, 0x5b, 0x72, 0x0e, 0x87, 0x51, 0xfe, 0xa5, 0x6c,
	0x0e, 0x53, 0x63, 0x69, 0x2f, 0x75, 0xed, 0x70, 0x14, 0x4b, 0x1d, 0x67, 0xcf, 0x00, 0xc6, 0x6a,
	0x43, 0xd6, 0x4b, 0x72, 0x38, 0x2e, 0xd2, 0x32, 0xbf, 0xb9, 0xae, 0x3a, 0xa7, 0xd5, 0x89, 0xcb,
	0xea, 0xad, 0x6b, 0x7c, 0x52, 0xde, 0x36, 0xfc, 0x64, 0x32, 0x38, 0x0a, 0x43, 0x38, 0x29, 0x92,
	0x72, 0xc6, 0x23, 0x0e, 0x3b, 0x18, 0x7d, 0x58, 0x08, 0xbb, 0x21, 0x8f, 0xd3, 0x22, 0x29, 0x47,
	0xbc, 0x17, 0xa2, 0x2b, 0x7d, 0x78, 0xd5, 0x6a, 0x45, 0x98, 0xc5, 0xc5, 0x3b, 0x1e, 0x5e, 0xdb,
	0x0a, 0xb7, 0x45, 0x68, 0xf7, 0x0b, 0x98, 0x5d, 0xc0, 0xd8, 0xd4, 0xcb, 0x17, 0x6a, 0x30, 0x8f,
	0xea, 0x91, 0x85, 0x5f, 0x9c, 0xdc, 0x28, 0xe1, 0x6b, 0x4b, 0x38, 0x6b, 0x93, 0xea, 0x84, 0xf9,
	0x03, 0xfc, 0xfb, 0x63, 0x3b, 0x84, 0xfd, 0x41, 0x4d, 0x0c, 0x3b, 0xe3, 0x01, 0xb2, 0x73, 0x18,
	0xed, 0xc5, 0x67, 0x4d, 0xc7, 0xa0, 0x5b, 0x72, 0x3f, 0xb8, 0x4b, 0x1e, 0xf3, 0xf7, 0xfe, 0x6a,
	0xcb, 0x71, 0xbc, 0xe3, 0xed, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xc0, 0xb2, 0x1d, 0xdc,
	0x01, 0x00, 0x00,
}
